CREATE TABLE landing_pages (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(120) NOT NULL UNIQUE,
  content_json JSON NULL,
  draft_json JSON NULL,
  status ENUM('draft','published','archived') DEFAULT 'draft',
  published_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE media_assets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  section VARCHAR(60) NULL,
  variant VARCHAR(60) NULL,
  original_name VARCHAR(180) NOT NULL,
  path VARCHAR(255) NOT NULL,
  url VARCHAR(500) NOT NULL,
  mime VARCHAR(60) NOT NULL,
  width INT UNSIGNED NULL,
  height INT UNSIGNED NULL,
  size_kb INT UNSIGNED NOT NULL,
  alt VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE landing_revisions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  landing_page_id BIGINT UNSIGNED NOT NULL,
  content_json JSON NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_landing_revisions_page FOREIGN KEY (landing_page_id) REFERENCES landing_pages(id) ON DELETE CASCADE,
  CONSTRAINT fk_landing_revisions_user FOREIGN KEY (created_by) REFERENCES usuarios(id) ON DELETE SET NULL
);
